pipeline:
  name: sample_project
description: Import labeled data from sample project from Superb.ai into Pachyderm
input:
  cron:
    name: "tick"
    spec: "@every 120s"
transform:
  cmd:
  - "/bin/sh"
  stdin:
  - python superb_import.py --project_name "Sample project"
  image: jimmywhitaker/superb_ai:0.1
  secrets:
  - name: superbai
    env_var: SPB_ACCOUNT_NAME
    key: account_name
  - name: superbai
    env_var: SPB_ACCESS_KEY
    key: access_key