FROM seldonio/seldon-core-s2i-python37-ubi8:1.7.0-dev

WORKDIR /workdir/
COPY . .
RUN pip install -r requirements.txt

# Install nltk dependencies
RUN python3 -m nltk.downloader stopwords
RUN python3 -m nltk.downloader punkt
RUN python3 -m nltk.downloader wordnet