singleuser:
  defaultUrl: "/lab"
  image:
    name: pachyderm/notebooks-user
    tag: v2.4.2
  extraEnv:
    "SIDECAR_MODE": "True"
  extraContainers:
    - name: mount-server-manager
      image: pachyderm/mount-server:2.4.2
      command: ["/bin/bash"]
      args: ["-c", "mount-server"]
      volumeMounts:
        - name: shared-pfs
          mountPath: /pfs
          mountPropagation: Bidirectional
      securityContext:
        privileged: true
        runAsUser: 0
  storage:
    extraVolumeMounts:
      - name: shared-pfs
        mountPath: /pfs
        mountPropagation: HostToContainer
    extraVolumes:
      - name: shared-pfs
        emptyDir: {}
